# yaml-language-server: $schema=../autocomplete/basic.json
job_steps: ['step_read', 'step_map_state_names', 'step_cast_customers', 'step_write']

debug: true

step_read:
  class_name: LocalReader
  config:
    file_path: "./examples/sales.csv"

step_map_state_names:
  class_name: Map
  config:
    name: 'state_abbreviation'
    map_dict_path: "./examples/states_to_abbreviation.json"
    col_key: 'region'
  
step_cast_customers:
  class_name: CastColumn
  config:
    cast_columns:
      customer_int: ['customers', 'integer']

step_write:
  class_name: LocalWriter
  config:
    file_path: "./output/output.csv"
