AWS_ACCESS_KEY_ID: AKIA3TOV3GZZHAH4MPAE
AWS_SECRET_ACCESS_KEY: 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

DATABRICKS_HOST: dbc-b854a7df-4e5e.cloud.databricks.com
DATABRICKS_TOKEN: dapi55908f285e31ab9937bc6928b4991fef
DATABRICKS_CLUSTER_ID: 0630-194840-lj2a32jr