AWS_ACCESS_KEY_ID: AKIA3TOV3GZZHAH4MPAE
AWS_SECRET_ACCESS_KEY: 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

DATABRICKS_HOST: dbc-b854a7df-4e5e.cloud.databricks.com
DATABRICKS_TOKEN: dapic439b3896eef6a09984c1ee0ed382d6e
DATABRICKS_CLUSTER_ID: 0630-194840-lj2a32jr